/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yunyunhei_mp3encoderdemo_studio_Mp3Encoder */

#ifndef _Included_cn_yunyunhei_mp3encoderdemo_studio_Mp3Encoder
#define _Included_cn_yunyunhei_mp3encoderdemo_studio_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yunyunhei_mp3encoderdemo_studio_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_yunyunhei_mp3encoderdemo_studio_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
