/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo */

#ifndef _Included_cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo
#define _Included_cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo
 * Method:    init
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

/*
 * Class:     cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo_encode
  (JNIEnv *, jobject);

/*
 * Class:     cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_yunyunhei_mp3encoderdemo_studio_Mp3EncoderTwo_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
